Add likes and dislikes functional
MiBBy-4/ideas_api_backend pull request #5
Opened 2022-02-22 13:29 UTC by MiBBy-4

2022-02-23 11:54 UTC, AndreyAnischik requested changes

2022-02-23 11:54 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +    if !@reaction.save
make the first condition positive `if @reaction.save`, also send the reaction back

2022-02-23 11:54 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +    idea = @reaction.idea
do you need this `idea`?

2022-02-23 11:54 UTC, AndreyAnischik commented on db/migrate/20220222102859_add_fields_to_customer_and_idea_tables.rb
> +    add_column :ideas, :avg_likes, :float
for what do we need these fields?

2022-02-23 11:59 UTC, MiBBy-4 commented on db/migrate/20220222102859_add_fields_to_customer_and_idea_tables.rb
> +    add_column :ideas, :avg_likes, :float
They are need for businessmen that answer on an idea. So, it was in my technical task.

2022-02-28 07:40 UTC, AndreyAnischik requested changes

2022-02-28 07:40 UTC, AndreyAnischik commented on db/migrate/20220222135354_add_boolean_filed_in_reactions_table.rb
> +    add_column :reactions, :reaction, :bool
rename the column please. is is strange that in reactions table there a reaction field.

2022-02-28 07:40 UTC, AndreyAnischik commented on db/migrate/20220222102859_add_fields_to_customer_and_idea_tables.rb
> +    add_column :ideas, :avg_likes, :float
can't you just count them when there is a need?

2022-02-28 07:40 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +    if Reaction.exists?(customer_id: session[:customer_id], idea_id: idea_id)
use `current_customer[:id]`

2022-02-28 07:40 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +      if exist_reaction.reaction === nil
exist_reaction.reaction.nil?

2022-02-28 07:40 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +          status: 'Change from nil to bool',
return existing http status, but also an instance of reaction

2022-02-28 07:40 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +        if (exist_reaction.reaction === true && @reaction.reaction === false) || (exist_reaction.reaction === false && @reaction.reaction === true)
`exist_reaction.reaction? && !@reaction.reaction?` ?

2022-02-28 07:40 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +            status: 'Bool reaction was changed'
add instance, return existing http status

2022-02-28 07:40 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +            status: 'Change to nil'
add instance, return existing http status

2022-02-28 07:40 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +          status: 500,
why 500?

2022-02-28 07:40 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +          status: :ok,
add instance

2022-03-02 10:48 UTC, AndreyAnischik requested changes

2022-03-02 10:48 UTC, AndreyAnischik commented on app/controllers/reactions_controller.rb
> +          status: 400,
why is it 400?

2022-03-03 07:38 UTC, AndreyAnischik approved these changes

2022-03-03 07:43 UTC, merged